/*
###############################################################
#  Generated by:      Cadence Innovus 20.13-s083_1
#  OS:                Linux x86_64(Host ID caddy14)
#  Generated on:      Sun Jun  6 23:21:31 2021
#  Design:            fine_freq_track
#  Command:           saveNetlist -excludeLeafCell results/fine_freq_track.vcs.v
###############################################################
*/
module delay_cell_osc (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module delay_cell_osc_SPC_1 (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module delay_cell_osc_SPC_2 (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module delay_cell_osc_SPC_3 (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module delay_cell_osc_SPC_4 (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module delay_cell_osc_SPC_5 (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module delay_cell_osc_SPC_6 (
	in, 
	en, 
	out);
   input in;
   input en;
   output out;

   sky130_fd_sc_hs__nand2_4 inand (.A(in),
	.B(en),
	.Y(out));
endmodule

module aux_core (
	glob_en, 
	osc_000, 
	osc_030, 
	osc_060, 
	osc_090, 
	osc_120, 
	osc_150, 
	osc_180);
   input glob_en;
   output osc_000;
   output osc_030;
   output osc_060;
   output osc_090;
   output osc_120;
   output osc_150;
   output osc_180;

   // Internal wires
   wire osc_90;

   delay_cell_osc del1 (.in(osc_000),
	.en(glob_en),
	.out(osc_030));
   delay_cell_osc_SPC_1 del2 (.in(osc_030),
	.en(glob_en),
	.out(osc_060));
   delay_cell_osc_SPC_2 del3 (.in(osc_060),
	.en(glob_en),
	.out(osc_90));
   delay_cell_osc_SPC_3 del4 (.in(osc_90),
	.en(glob_en),
	.out(osc_120));
   delay_cell_osc_SPC_4 del5 (.in(osc_120),
	.en(glob_en),
	.out(osc_150));
   delay_cell_osc_SPC_5 del6 (.in(osc_150),
	.en(glob_en),
	.out(osc_180));
   delay_cell_osc_SPC_6 del7 (.in(osc_180),
	.en(glob_en),
	.out(osc_000));
endmodule

module SNPS_CLOCK_GATE_HIGH_fine_freq_track_0 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   // Internal wires
   wire LTIE_LONET;

   sky130_fd_sc_hs__conb_1 LTIE (.LO(LTIE_LONET));
   sky130_fd_sc_hs__sdlclkp_1 latch (.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(LTIE_LONET));
endmodule

module SNPS_CLOCK_GATE_HIGH_fine_freq_track_1 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   // Internal wires
   wire LTIE_LONET;

   sky130_fd_sc_hs__conb_1 LTIE (.LO(LTIE_LONET));
   sky130_fd_sc_hs__sdlclkp_4 latch (.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(LTIE_LONET));
endmodule

module fine_freq_track (
	clk_out, 
	div_ratio_half, 
	ref_clk, 
	rst, 
	aux_osc_en, 
	fine_control_avg_window_select, 
	fine_con_step_size, 
	out_star, 
	osc_fine_con);
   input clk_out;
   input [5:0] div_ratio_half;
   input ref_clk;
   input rst;
   input aux_osc_en;
   input [4:0] fine_control_avg_window_select;
   input [3:0] fine_con_step_size;
   output out_star;
   output [7:0] osc_fine_con;

   // Internal wires
   wire FE_PSN4_div_ratio_half_0;
   wire FE_PSN3_div_ratio_half_1;
   wire FE_PSN2_n137;
   wire FE_PSN1_n136;
   wire FE_PSN0_n259;
   wire FE_RN_11_0;
   wire FE_OCPN3_n259;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire FE_OFN2_accumu_select;
   wire FE_OFN1_n2210;
   wire FE_OFN0_n2210;
   wire accumu_select;
   wire sync_flag;
   wire N54;
   wire aux_clk_out;
   wire N72;
   wire N73;
   wire N74;
   wire N75;
   wire N76;
   wire N77;
   wire N78;
   wire N79;
   wire N80;
   wire N81;
   wire N82;
   wire N83;
   wire N84;
   wire N85;
   wire N86;
   wire N87;
   wire N88;
   wire N89;
   wire N90;
   wire N91;
   wire N92;
   wire N93;
   wire N94;
   wire N95;
   wire N96;
   wire N97;
   wire N98;
   wire N99;
   wire N100;
   wire N101;
   wire N102;
   wire commit_clk;
   wire N202;
   wire N203;
   wire N204;
   wire N205;
   wire N206;
   wire N207;
   wire N208;
   wire N209;
   wire N210;
   wire N211;
   wire N212;
   wire N213;
   wire N214;
   wire N215;
   wire N216;
   wire N217;
   wire N218;
   wire N219;
   wire N220;
   wire N221;
   wire N222;
   wire N223;
   wire N224;
   wire N225;
   wire N226;
   wire N227;
   wire N228;
   wire N229;
   wire N230;
   wire N231;
   wire N232;
   wire N233;
   wire N234;
   wire N235;
   wire N236;
   wire N237;
   wire N238;
   wire N239;
   wire N240;
   wire N241;
   wire N242;
   wire N243;
   wire N244;
   wire N245;
   wire N246;
   wire N247;
   wire N248;
   wire N249;
   wire N250;
   wire N251;
   wire CurrentState_1_;
   wire N286;
   wire N287;
   wire N288;
   wire N289;
   wire N290;
   wire N291;
   wire N292;
   wire N294;
   wire net789;
   wire net793;
   wire net804;
   wire esample_DF;
   wire esample_N2;
   wire esample_DR;
   wire esample_osc_out_star_b;
   wire C19_DATA2_0;
   wire C19_DATA2_1;
   wire C19_DATA2_2;
   wire C19_DATA2_3;
   wire C19_DATA2_4;
   wire C19_DATA2_5;
   wire C19_DATA2_6;
   wire n4;
   wire n6;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n960;
   wire DP_OP_67J1_123_9407_n25;
   wire DP_OP_67J1_123_9407_n16;
   wire DP_OP_67J1_123_9407_n15;
   wire DP_OP_67J1_123_9407_n14;
   wire DP_OP_67J1_123_9407_n13;
   wire DP_OP_67J1_123_9407_n8;
   wire DP_OP_67J1_123_9407_n7;
   wire DP_OP_67J1_123_9407_n6;
   wire DP_OP_67J1_123_9407_n5;
   wire DP_OP_67J1_123_9407_n4;
   wire DP_OP_67J1_123_9407_n3;
   wire DP_OP_67J1_123_9407_n2;
   wire n122;
   wire n124;
   wire n125;
   wire n126;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n191;
   wire n193;
   wire n194;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n2020;
   wire n2030;
   wire n2040;
   wire n2050;
   wire n2060;
   wire n2070;
   wire n2080;
   wire n2090;
   wire n2100;
   wire n2110;
   wire n2120;
   wire n2130;
   wire n2140;
   wire n2150;
   wire n2160;
   wire n2170;
   wire n2180;
   wire n2190;
   wire n2200;
   wire n2210;
   wire n2250;
   wire n2260;
   wire n2270;
   wire n2280;
   wire n2290;
   wire n2300;
   wire n2310;
   wire n2320;
   wire n2330;
   wire n2340;
   wire n2350;
   wire n2360;
   wire n2370;
   wire n2380;
   wire n2390;
   wire n2400;
   wire n2410;
   wire n2420;
   wire n2430;
   wire n2440;
   wire n2450;
   wire n2460;
   wire n2470;
   wire n2480;
   wire n2490;
   wire n2500;
   wire n2510;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n263;
   wire n265;
   wire n266;
   wire n267;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n2860;
   wire n2870;
   wire n2880;
   wire n2890;
   wire n2900;
   wire n2910;
   wire n2920;
   wire n293;
   wire n2940;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n327;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n344;
   wire n345;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n514;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n532;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n562;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n573;
   wire n574;
   wire n575;
   wire n576;
   wire n577;
   wire n578;
   wire n579;
   wire n580;
   wire n581;
   wire n582;
   wire n583;
   wire n584;
   wire n585;
   wire n586;
   wire n588;
   wire n590;
   wire n591;
   wire n592;
   wire n599;
   wire [5:0] osc_clk_count;
   wire [31:0] commit_clk_cnt;
   wire [1:0] stat_error;
   wire [2:0] stat_clean;
   wire [1:0] NextState;

   sky130_fd_sc_hs__buf_2 FE_PSC4_div_ratio_half_0 (.A(div_ratio_half[0]),
	.X(FE_PSN4_div_ratio_half_0));
   sky130_fd_sc_hs__buf_2 FE_PSC3_div_ratio_half_1 (.A(div_ratio_half[1]),
	.X(FE_PSN3_div_ratio_half_1));
   sky130_fd_sc_hs__buf_2 FE_PSC2_n137 (.A(n137),
	.X(FE_PSN2_n137));
   sky130_fd_sc_hs__clkbuf_2 FE_PSC1_n136 (.A(n136),
	.X(FE_PSN1_n136));
   sky130_fd_sc_hs__buf_1 FE_PSC0_n259 (.A(n259),
	.X(FE_PSN0_n259));
   sky130_fd_sc_hs__o21ai_2 FE_RC_45_0 (.A1(n129),
	.A2(n134),
	.B1(n137),
	.Y(n130));
   sky130_fd_sc_hs__xnor2_2 FE_RC_44_0 (.A(osc_clk_count[2]),
	.B(n130),
	.Y(n131));
   sky130_fd_sc_hs__nor2_2 FE_RC_43_0 (.A(rst),
	.B(sync_flag),
	.Y(FE_RN_11_0));
   sky130_fd_sc_hs__nand2b_2 FE_RC_42_0 (.A_N(FE_OCPN3_n259),
	.B(FE_RN_11_0),
	.Y(net789));
   sky130_fd_sc_hs__inv_2 FE_OCPC5_n259 (.A(n259),
	.Y(FE_OCPN3_n259));
   sky130_fd_sc_hs__nand4_2 FE_RC_41_0 (.A(n272),
	.B(n166),
	.C(N241),
	.D(n306),
	.Y(n167));
   sky130_fd_sc_hs__nor4_1 FE_RC_40_0 (.A(n271),
	.B(n270),
	.C(FE_RN_5_0),
	.D(FE_OCPN3_n259),
	.Y(n9));
   sky130_fd_sc_hs__nand2b_1 FE_RC_38_0 (.A_N(rst),
	.B(n194),
	.Y(FE_RN_10_0));
   sky130_fd_sc_hs__nor2b_1 FE_RC_37_0 (.A(FE_RN_10_0),
	.B_N(n259),
	.Y(n11));
   sky130_fd_sc_hs__and2_2 FE_RC_36_0 (.A(n257),
	.B(n258),
	.X(FE_RN_9_0));
   sky130_fd_sc_hs__nor3_1 FE_RC_35_0 (.A(n271),
	.B(FE_RN_9_0),
	.C(FE_OCPN3_n259),
	.Y(N54));
   sky130_fd_sc_hs__o2bb2ai_1 FE_RC_34_0 (.A1_N(n586),
	.A2_N(n599),
	.B1(n586),
	.B2(n599),
	.Y(FE_RN_7_0));
   sky130_fd_sc_hs__nand2b_1 FE_RC_33_0 (.A_N(rst),
	.B(FE_RN_7_0),
	.Y(FE_RN_8_0));
   sky130_fd_sc_hs__nor2_2 FE_RC_32_0 (.A(FE_RN_8_0),
	.B(n263),
	.Y(n10));
   sky130_fd_sc_hs__nor4b_1 FE_RC_31_0 (.A(n271),
	.B(rst),
	.C(osc_clk_count[0]),
	.D_N(FE_PSN0_n259),
	.Y(n13));
   sky130_fd_sc_hs__inv_2 FE_RC_29_0 (.A(rst),
	.Y(FE_RN_6_0));
   sky130_fd_sc_hs__nor3b_1 FE_RC_28_0 (.A(n263),
	.B(n260),
	.C_N(FE_RN_6_0),
	.Y(n8));
   sky130_fd_sc_hs__or2_1 FE_RC_27_0 (.A(n269),
	.B(rst),
	.X(FE_RN_5_0));
   sky130_fd_sc_hs__o21ai_2 FE_RC_23_0 (.A1(div_ratio_half[3]),
	.A2(n586),
	.B1(n136),
	.Y(n138));
   sky130_fd_sc_hs__nand2_1 FE_RC_22_0 (.A(n258),
	.B(n128),
	.Y(FE_RN_3_0));
   sky130_fd_sc_hs__nand2_2 FE_RC_21_0 (.A(FE_RN_3_0),
	.B(n131),
	.Y(n142));
   sky130_fd_sc_hs__inv_1 FE_RC_19_0 (.A(N54),
	.Y(FE_RN_2_0));
   sky130_fd_sc_hs__nor2_1 FE_RC_18_0 (.A(rst),
	.B(FE_RN_2_0),
	.Y(n12));
   sky130_fd_sc_hs__nor3_2 FE_RC_17_0 (.A(n2500),
	.B(n322),
	.C(n255),
	.Y(n252));
   sky130_fd_sc_hs__o2bb2ai_2 FE_RC_16_0 (.A1_N(div_ratio_half[4]),
	.A2_N(osc_clk_count[4]),
	.B1(div_ratio_half[4]),
	.B2(osc_clk_count[4]),
	.Y(n122));
   sky130_fd_sc_hs__a2bb2oi_2 FE_RC_15_0 (.A1_N(n135),
	.A2_N(osc_clk_count[1]),
	.B1(FE_PSN4_div_ratio_half_0),
	.B2(osc_clk_count[0]),
	.Y(n140));
   sky130_fd_sc_hs__clkinv_1 FE_OCPC3_n10 (.A(n10),
	.Y(n543));
   sky130_fd_sc_hs__nand2b_1 FE_RC_14_0 (.A_N(n303),
	.B(stat_clean[1]),
	.Y(n305));
   sky130_fd_sc_hs__clkinv_1 FE_RC_13_0 (.A(n402),
	.Y(FE_RN_0_0));
   sky130_fd_sc_hs__clkinv_1 FE_RC_12_0 (.A(N222),
	.Y(FE_RN_1_0));
   sky130_fd_sc_hs__a211o_2 FE_RC_11_0 (.A1(FE_RN_1_0),
	.A2(N247),
	.B1(n415),
	.C1(FE_RN_0_0),
	.X(n414));
   sky130_fd_sc_hs__nor2b_1 FE_RC_10_0 (.A(n408),
	.B_N(n404),
	.Y(n411));
   sky130_fd_sc_hs__nor3b_1 FE_RC_9_0 (.A(n390),
	.B(n363),
	.C_N(n385),
	.Y(n313));
   sky130_fd_sc_hs__nor2b_1 FE_RC_8_0 (.A(N247),
	.B_N(N222),
	.Y(n403));
   sky130_fd_sc_hs__nor2b_1 FE_RC_7_0 (.A(N250),
	.B_N(N225),
	.Y(n362));
   sky130_fd_sc_hs__nand2b_1 FE_RC_6_0 (.A_N(N213),
	.B(N238),
	.Y(n389));
   sky130_fd_sc_hs__nand2b_1 FE_RC_5_0 (.A_N(n368),
	.B(n336),
	.Y(n369));
   sky130_fd_sc_hs__nor2b_1 FE_RC_4_0 (.A(N246),
	.B_N(N221),
	.Y(n412));
   sky130_fd_sc_hs__nand2b_1 FE_RC_3_0 (.A_N(N238),
	.B(N213),
	.Y(n385));
   sky130_fd_sc_hs__nor2b_1 FE_RC_2_0 (.A(N221),
	.B_N(N246),
	.Y(n410));
   sky130_fd_sc_hs__and3b_1 FE_RC_1_0 (.A_N(n586),
	.B(osc_clk_count[4]),
	.C(n599),
	.X(n270));
   sky130_fd_sc_hs__a21boi_1 FE_RC_0_0 (.A1(osc_clk_count[1]),
	.A2(FE_PSN4_div_ratio_half_0),
	.B1_N(div_ratio_half[1]),
	.Y(n128));
   sky130_fd_sc_hs__clkbuf_2 FE_OFC2_accumu_select (.A(accumu_select),
	.X(FE_OFN2_accumu_select));
   sky130_fd_sc_hs__clkbuf_8 FE_OFC1_n2210 (.A(FE_OFN0_n2210),
	.X(FE_OFN1_n2210));
   sky130_fd_sc_hs__clkbuf_8 FE_OFC0_n2210 (.A(n2210),
	.X(FE_OFN0_n2210));
   aux_core aux_osc (.glob_en(aux_osc_en),
	.osc_000(aux_clk_out));
   SNPS_CLOCK_GATE_HIGH_fine_freq_track_0 clk_gate_osc_clk_count_reg_5_ (.CLK(clk_out),
	.EN(net789),
	.ENCLK(net793));
   SNPS_CLOCK_GATE_HIGH_fine_freq_track_1 clk_gate_osc_fine_con_reg_7_ (.CLK(commit_clk),
	.EN(N294),
	.ENCLK(net804));
   sky130_fd_sc_hs__dfrtn_1 stat_error_reg_1_ (.CLK_N(ref_clk),
	.D(N203),
	.Q(stat_error[1]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtn_1 stat_error_reg_0_ (.CLK_N(ref_clk),
	.D(N202),
	.Q(stat_error[0]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__nor2b_1 U6 (.A(rst),
	.B_N(esample_N2),
	.Y(n4));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U9 (.A(osc_fine_con[0]),
	.B(DP_OP_67J1_123_9407_n25),
	.CIN(DP_OP_67J1_123_9407_n16),
	.COUT(DP_OP_67J1_123_9407_n8),
	.SUM(C19_DATA2_0));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U8 (.A(DP_OP_67J1_123_9407_n15),
	.B(osc_fine_con[1]),
	.CIN(DP_OP_67J1_123_9407_n8),
	.COUT(DP_OP_67J1_123_9407_n7),
	.SUM(C19_DATA2_1));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U7 (.A(DP_OP_67J1_123_9407_n14),
	.B(osc_fine_con[2]),
	.CIN(DP_OP_67J1_123_9407_n7),
	.COUT(DP_OP_67J1_123_9407_n6),
	.SUM(C19_DATA2_2));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U6 (.A(DP_OP_67J1_123_9407_n13),
	.B(osc_fine_con[3]),
	.CIN(DP_OP_67J1_123_9407_n6),
	.COUT(DP_OP_67J1_123_9407_n5),
	.SUM(C19_DATA2_3));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U5 (.A(DP_OP_67J1_123_9407_n25),
	.B(osc_fine_con[4]),
	.CIN(DP_OP_67J1_123_9407_n5),
	.COUT(DP_OP_67J1_123_9407_n4),
	.SUM(C19_DATA2_4));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U4 (.A(DP_OP_67J1_123_9407_n25),
	.B(osc_fine_con[5]),
	.CIN(DP_OP_67J1_123_9407_n4),
	.COUT(DP_OP_67J1_123_9407_n3),
	.SUM(C19_DATA2_5));
   sky130_fd_sc_hs__fa_2 DP_OP_67J1_123_9407_U3 (.A(DP_OP_67J1_123_9407_n25),
	.B(osc_fine_con[6]),
	.CIN(DP_OP_67J1_123_9407_n3),
	.COUT(DP_OP_67J1_123_9407_n2),
	.SUM(C19_DATA2_6));
   sky130_fd_sc_hs__dfstp_2 R_174 (.CLK(n484),
	.D(n571),
	.Q(n467),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfxtp_4 esample_DR_reg (.CLK(out_star),
	.D(n4),
	.Q(esample_DR));
   sky130_fd_sc_hs__dfxtp_4 esample_DF_reg (.CLK(esample_osc_out_star_b),
	.D(n4),
	.Q(esample_DF));
   sky130_fd_sc_hs__dfrbp_1 stat_clean_reg_1_ (.CLK(ref_clk),
	.D(N228),
	.Q(stat_clean[1]),
	.Q_N(n446),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrbp_1 stat_clean_reg_2_ (.CLK(ref_clk),
	.D(N229),
	.Q(stat_clean[2]),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__nand2_1 U130 (.A(n122),
	.B(FE_PSN2_n137),
	.Y(n125));
   sky130_fd_sc_hs__nand2_1 U132 (.A(n146),
	.B(osc_clk_count[3]),
	.Y(n124));
   sky130_fd_sc_hs__inv_2 U136 (.A(osc_clk_count[1]),
	.Y(n126));
   sky130_fd_sc_hs__nand2_2 U137 (.A(n126),
	.B(osc_clk_count[0]),
	.Y(n258));
   sky130_fd_sc_hs__nand2_2 U145 (.A(n133),
	.B(osc_clk_count[1]),
	.Y(n257));
   sky130_fd_sc_hs__nand2_2 U149 (.A(n138),
	.B(FE_PSN2_n137),
	.Y(n139));
   sky130_fd_sc_hs__o211ai_2 U150 (.A1(FE_PSN3_div_ratio_half_1),
	.A2(n257),
	.B1(n140),
	.C1(n139),
	.Y(n141));
   sky130_fd_sc_hs__nand2_1 U153 (.A(osc_clk_count[4]),
	.B(n143),
	.Y(n145));
   sky130_fd_sc_hs__xnor2_1 U154 (.A(div_ratio_half[5]),
	.B(osc_clk_count[5]),
	.Y(n144));
   sky130_fd_sc_hs__xnor2_1 U155 (.A(n145),
	.B(n144),
	.Y(n148));
   sky130_fd_sc_hs__nand2_1 U156 (.A(n146),
	.B(div_ratio_half[3]),
	.Y(n147));
   sky130_fd_sc_hs__nand4_2 U157 (.A(n149),
	.B(n150),
	.C(n148),
	.D(n147),
	.Y(n259));
   sky130_fd_sc_hs__nand2_1 U169 (.A(n462),
	.B(n452),
	.Y(n151));
   sky130_fd_sc_hs__xnor2_1 U170 (.A(n495),
	.B(n151),
	.Y(N243));
   sky130_fd_sc_hs__xnor2_1 U171 (.A(n452),
	.B(n490),
	.Y(N242));
   sky130_fd_sc_hs__and2_2 U172 (.A(N243),
	.B(N242),
	.X(n561));
   sky130_fd_sc_hs__xnor2_1 U173 (.A(n453),
	.B(n498),
	.Y(N244));
   sky130_fd_sc_hs__nand3_1 U174 (.A(n462),
	.B(n476),
	.C(n453),
	.Y(n152));
   sky130_fd_sc_hs__xnor2_1 U175 (.A(n510),
	.B(n152),
	.Y(N245));
   sky130_fd_sc_hs__nand3_1 U176 (.A(n561),
	.B(N244),
	.C(N245),
	.Y(n563));
   sky130_fd_sc_hs__nand2_1 U179 (.A(n157),
	.B(n449),
	.Y(n153));
   sky130_fd_sc_hs__xnor2_1 U180 (.A(n520),
	.B(n153),
	.Y(N235));
   sky130_fd_sc_hs__nor2_1 U181 (.A(n470),
	.B(n461),
	.Y(n154));
   sky130_fd_sc_hs__xor2_1 U182 (.A(n514),
	.B(n154),
	.X(N236));
   sky130_fd_sc_hs__xnor2_1 U183 (.A(n449),
	.B(n461),
	.Y(N234));
   sky130_fd_sc_hs__nand2_1 U184 (.A(N235),
	.B(N234),
	.Y(n554));
   sky130_fd_sc_hs__nor2_1 U186 (.A(n318),
	.B(n554),
	.Y(n555));
   sky130_fd_sc_hs__nand2_1 U187 (.A(n157),
	.B(n488),
	.Y(n155));
   sky130_fd_sc_hs__xnor2_1 U188 (.A(n519),
	.B(n155),
	.Y(N237));
   sky130_fd_sc_hs__and2_2 U189 (.A(n555),
	.B(N237),
	.X(n556));
   sky130_fd_sc_hs__nand3_1 U190 (.A(n157),
	.B(n502),
	.C(n450),
	.Y(n156));
   sky130_fd_sc_hs__nand2_1 U192 (.A(n157),
	.B(n487),
	.Y(n158));
   sky130_fd_sc_hs__xnor2_1 U196 (.A(n493),
	.B(n159),
	.Y(N233));
   sky130_fd_sc_hs__nor3_1 U197 (.A(n491),
	.B(n461),
	.C(n451),
	.Y(n160));
   sky130_fd_sc_hs__xor2_1 U198 (.A(n527),
	.B(n160),
	.X(N241));
   sky130_fd_sc_hs__nor2_1 U199 (.A(n461),
	.B(n451),
	.Y(n161));
   sky130_fd_sc_hs__xor2_1 U200 (.A(n515),
	.B(n161),
	.X(N240));
   sky130_fd_sc_hs__xnor2_1 U201 (.A(n448),
	.B(n489),
	.Y(n349));
   sky130_fd_sc_hs__nor2_1 U202 (.A(n162),
	.B(n349),
	.Y(n163));
   sky130_fd_sc_hs__and2_2 U203 (.A(n163),
	.B(N233),
	.X(n306));
   sky130_fd_sc_hs__nand2_1 U204 (.A(stat_clean[0]),
	.B(N240),
	.Y(n165));
   sky130_fd_sc_hs__nor2_1 U205 (.A(n165),
	.B(n164),
	.Y(n166));
   sky130_fd_sc_hs__nor2_2 U214 (.A(CurrentState_1_),
	.B(n169),
	.Y(DP_OP_67J1_123_9407_n25));
   sky130_fd_sc_hs__nand3_1 U215 (.A(n462),
	.B(n480),
	.C(n454),
	.Y(n170));
   sky130_fd_sc_hs__xnor2_1 U216 (.A(n508),
	.B(n170),
	.Y(N251));
   sky130_fd_sc_hs__nand2_2 U217 (.A(n460),
	.B(n464),
	.Y(n182));
   sky130_fd_sc_hs__nor2_1 U218 (.A(n486),
	.B(n182),
	.Y(n183));
   sky130_fd_sc_hs__xor2_1 U219 (.A(n517),
	.B(n183),
	.X(N221));
   sky130_fd_sc_hs__inv_4 U220 (.A(n182),
	.Y(n266));
   sky130_fd_sc_hs__nand3_1 U221 (.A(n266),
	.B(n457),
	.C(n505),
	.Y(n171));
   sky130_fd_sc_hs__xnor2_1 U222 (.A(n533),
	.B(n171),
	.Y(N222));
   sky130_fd_sc_hs__nor2_1 U223 (.A(n456),
	.B(n182),
	.Y(n172));
   sky130_fd_sc_hs__xor2_1 U224 (.A(n512),
	.B(n172),
	.X(N219));
   sky130_fd_sc_hs__nand3b_1 U225 (.A_N(n456),
	.B(n266),
	.C(n503),
	.Y(n173));
   sky130_fd_sc_hs__xnor2_1 U226 (.A(n532),
	.B(n173),
	.Y(N220));
   sky130_fd_sc_hs__nand2_1 U227 (.A(n462),
	.B(n465),
	.Y(n174));
   sky130_fd_sc_hs__xnor2_1 U228 (.A(n499),
	.B(n174),
	.Y(N246));
   sky130_fd_sc_hs__nand2_1 U229 (.A(n266),
	.B(n492),
	.Y(n175));
   sky130_fd_sc_hs__xnor2_1 U230 (.A(n529),
	.B(n175),
	.Y(N218));
   sky130_fd_sc_hs__nand3_1 U231 (.A(n266),
	.B(n457),
	.C(n458),
	.Y(n176));
   sky130_fd_sc_hs__xnor2_1 U232 (.A(n531),
	.B(n176),
	.Y(N223));
   sky130_fd_sc_hs__nand3b_1 U233 (.A_N(n472),
	.B(n462),
	.C(n471),
	.Y(n177));
   sky130_fd_sc_hs__xnor2_1 U234 (.A(n506),
	.B(n177),
	.Y(N247));
   sky130_fd_sc_hs__nand2_2 U235 (.A(n467),
	.B(n466),
	.Y(n2450));
   sky130_fd_sc_hs__nor2_1 U236 (.A(n2450),
	.B(n513),
	.Y(n2480));
   sky130_fd_sc_hs__nand2_1 U237 (.A(n2480),
	.B(n516),
	.Y(n178));
   sky130_fd_sc_hs__xnor2_1 U238 (.A(n538),
	.B(n178),
	.Y(N212));
   sky130_fd_sc_hs__nand2_1 U239 (.A(n2480),
	.B(n460),
	.Y(n179));
   sky130_fd_sc_hs__xnor2_1 U240 (.A(n540),
	.B(n179),
	.Y(N213));
   sky130_fd_sc_hs__inv_4 U242 (.A(n2450),
	.Y(n2460));
   sky130_fd_sc_hs__nand2_1 U243 (.A(n2460),
	.B(n482),
	.Y(n180));
   sky130_fd_sc_hs__xnor2_1 U244 (.A(n522),
	.B(n180),
	.Y(N206));
   sky130_fd_sc_hs__nand2_1 U245 (.A(n2480),
	.B(n518),
	.Y(n181));
   sky130_fd_sc_hs__xnor2_1 U246 (.A(n539),
	.B(n181),
	.Y(N210));
   sky130_fd_sc_hs__xnor2_1 U247 (.A(n511),
	.B(n182),
	.Y(N217));
   sky130_fd_sc_hs__nand3_1 U248 (.A(n183),
	.B(n500),
	.C(n458),
	.Y(n184));
   sky130_fd_sc_hs__xnor2_1 U249 (.A(n534),
	.B(n184),
	.Y(N224));
   sky130_fd_sc_hs__nand2_1 U250 (.A(n266),
	.B(n459),
	.Y(n185));
   sky130_fd_sc_hs__xnor2_1 U251 (.A(n528),
	.B(n185),
	.Y(N225));
   sky130_fd_sc_hs__nand2_1 U254 (.A(N204),
	.B(stat_error[1]),
	.Y(n2500));
   sky130_fd_sc_hs__inv_4 U255 (.A(n2500),
	.Y(n570));
   sky130_fd_sc_hs__nand2_1 U257 (.A(N218),
	.B(N217),
	.Y(n580));
   sky130_fd_sc_hs__nand3b_1 U258 (.A_N(n580),
	.B(N219),
	.C(N220),
	.Y(n583));
   sky130_fd_sc_hs__inv_4 U259 (.A(n583),
	.Y(n581));
   sky130_fd_sc_hs__nor2_1 U261 (.A(n526),
	.B(n2430),
	.Y(n186));
   sky130_fd_sc_hs__xor2_1 U262 (.A(n536),
	.B(n186),
	.X(N211));
   sky130_fd_sc_hs__nand2_1 U263 (.A(n455),
	.B(n2480),
	.Y(n187));
   sky130_fd_sc_hs__xnor2_1 U264 (.A(n537),
	.B(n187),
	.Y(N215));
   sky130_fd_sc_hs__nand3_1 U265 (.A(n455),
	.B(n525),
	.C(n2480),
	.Y(n188));
   sky130_fd_sc_hs__xnor2_1 U266 (.A(n541),
	.B(n188),
	.Y(N216));
   sky130_fd_sc_hs__inv_4 U267 (.A(sync_flag),
	.Y(n271));
   sky130_fd_sc_hs__and2_2 U271 (.A(osc_clk_count[0]),
	.B(osc_clk_count[1]),
	.X(n191));
   sky130_fd_sc_hs__o21ai_1 U272 (.A1(osc_clk_count[2]),
	.A2(n191),
	.B1(sync_flag),
	.Y(n193));
   sky130_fd_sc_hs__nor2_1 U275 (.A(n193),
	.B(n599),
	.Y(n194));
   sky130_fd_sc_hs__nor2_1 U279 (.A(fine_control_avg_window_select[3]),
	.B(fine_control_avg_window_select[4]),
	.Y(n436));
   sky130_fd_sc_hs__and2_2 U280 (.A(fine_control_avg_window_select[3]),
	.B(fine_control_avg_window_select[4]),
	.X(n434));
   sky130_fd_sc_hs__nor2b_1 U281 (.A(fine_control_avg_window_select[4]),
	.B_N(fine_control_avg_window_select[3]),
	.Y(n432));
   sky130_fd_sc_hs__nor2b_1 U282 (.A(fine_control_avg_window_select[3]),
	.B_N(fine_control_avg_window_select[4]),
	.Y(n433));
   sky130_fd_sc_hs__a222o_1 U283 (.A1(commit_clk_cnt[25]),
	.A2(n434),
	.B1(commit_clk_cnt[9]),
	.B2(n432),
	.C1(commit_clk_cnt[17]),
	.C2(n433),
	.X(n435));
   sky130_fd_sc_hs__a21oi_1 U284 (.A1(commit_clk_cnt[25]),
	.A2(n436),
	.B1(n435),
	.Y(n2030));
   sky130_fd_sc_hs__a22oi_1 U285 (.A1(commit_clk_cnt[19]),
	.A2(n433),
	.B1(commit_clk_cnt[11]),
	.B2(n432),
	.Y(n197));
   sky130_fd_sc_hs__a22oi_1 U286 (.A1(commit_clk_cnt[27]),
	.A2(n434),
	.B1(commit_clk_cnt[3]),
	.B2(n436),
	.Y(n196));
   sky130_fd_sc_hs__a21oi_1 U287 (.A1(n197),
	.A2(n196),
	.B1(fine_control_avg_window_select[2]),
	.Y(n2020));
   sky130_fd_sc_hs__a22oi_1 U288 (.A1(commit_clk_cnt[21]),
	.A2(n433),
	.B1(commit_clk_cnt[13]),
	.B2(n432),
	.Y(n200));
   sky130_fd_sc_hs__a22oi_1 U289 (.A1(commit_clk_cnt[29]),
	.A2(n434),
	.B1(commit_clk_cnt[5]),
	.B2(n436),
	.Y(n199));
   sky130_fd_sc_hs__nand2_1 U291 (.A(fine_control_avg_window_select[2]),
	.B(n427),
	.Y(n198));
   sky130_fd_sc_hs__a21oi_1 U292 (.A1(n200),
	.A2(n199),
	.B1(n198),
	.Y(n201));
   sky130_fd_sc_hs__a21oi_1 U293 (.A1(fine_control_avg_window_select[1]),
	.A2(n2020),
	.B1(n201),
	.Y(n430));
   sky130_fd_sc_hs__o31ai_1 U294 (.A1(n2030),
	.A2(fine_control_avg_window_select[2]),
	.A3(fine_control_avg_window_select[1]),
	.B1(n430),
	.Y(n2200));
   sky130_fd_sc_hs__inv_4 U295 (.A(fine_control_avg_window_select[2]),
	.Y(n2130));
   sky130_fd_sc_hs__a22oi_1 U296 (.A1(commit_clk_cnt[20]),
	.A2(n433),
	.B1(commit_clk_cnt[12]),
	.B2(n432),
	.Y(n2050));
   sky130_fd_sc_hs__a22oi_1 U297 (.A1(commit_clk_cnt[28]),
	.A2(n434),
	.B1(commit_clk_cnt[4]),
	.B2(n436),
	.Y(n2040));
   sky130_fd_sc_hs__a22oi_1 U299 (.A1(commit_clk_cnt[14]),
	.A2(n432),
	.B1(commit_clk_cnt[6]),
	.B2(n436),
	.Y(n2120));
   sky130_fd_sc_hs__nand2_1 U300 (.A(commit_clk_cnt[30]),
	.B(n434),
	.Y(n429));
   sky130_fd_sc_hs__a211oi_1 U302 (.A1(n433),
	.A2(commit_clk_cnt[22]),
	.B1(n2060),
	.C1(n2130),
	.Y(n2110));
   sky130_fd_sc_hs__a22oi_1 U305 (.A1(commit_clk_cnt[18]),
	.A2(n433),
	.B1(commit_clk_cnt[10]),
	.B2(n432),
	.Y(n2080));
   sky130_fd_sc_hs__a21oi_1 U306 (.A1(n434),
	.A2(commit_clk_cnt[26]),
	.B1(fine_control_avg_window_select[2]),
	.Y(n2070));
   sky130_fd_sc_hs__o211a_2 U307 (.A1(n2400),
	.A2(n2090),
	.B1(n2080),
	.C1(n2070),
	.X(n2100));
   sky130_fd_sc_hs__a21oi_1 U308 (.A1(n2120),
	.A2(n2110),
	.B1(n2100),
	.Y(n425));
   sky130_fd_sc_hs__a32oi_1 U309 (.A1(n2130),
	.A2(fine_control_avg_window_select[1]),
	.A3(n426),
	.B1(n425),
	.B2(n427),
	.Y(n2180));
   sky130_fd_sc_hs__a222oi_1 U310 (.A1(commit_clk_cnt[23]),
	.A2(n433),
	.B1(commit_clk_cnt[15]),
	.B2(n432),
	.C1(commit_clk_cnt[7]),
	.C2(n436),
	.Y(n431));
   sky130_fd_sc_hs__nor2_1 U311 (.A(fine_control_avg_window_select[0]),
	.B(n431),
	.Y(n2160));
   sky130_fd_sc_hs__a222oi_1 U312 (.A1(commit_clk_cnt[24]),
	.A2(n433),
	.B1(commit_clk_cnt[16]),
	.B2(n432),
	.C1(commit_clk_cnt[8]),
	.C2(n436),
	.Y(n2140));
   sky130_fd_sc_hs__o2bb2ai_1 U313 (.A1_N(commit_clk_cnt[31]),
	.A2_N(n434),
	.B1(n2140),
	.B2(n439),
	.Y(n2150));
   sky130_fd_sc_hs__nand2_1 U314 (.A(fine_control_avg_window_select[1]),
	.B(fine_control_avg_window_select[2]),
	.Y(n428));
   sky130_fd_sc_hs__o21bai_1 U315 (.A1(n2160),
	.A2(n2150),
	.B1_N(n428),
	.Y(n2170));
   sky130_fd_sc_hs__o211ai_1 U316 (.A1(n2180),
	.A2(n439),
	.B1(FE_RN_6_0),
	.C1(n2170),
	.Y(n2190));
   sky130_fd_sc_hs__nor2b_1 U328 (.A(CurrentState_1_),
	.B_N(C19_DATA2_2),
	.Y(N288));
   sky130_fd_sc_hs__nand2_2 U336 (.A(commit_clk_cnt[1]),
	.B(commit_clk_cnt[0]),
	.Y(n273));
   sky130_fd_sc_hs__nor2_1 U337 (.A(n2400),
	.B(n273),
	.Y(n275));
   sky130_fd_sc_hs__nand2_1 U338 (.A(commit_clk_cnt[3]),
	.B(n275),
	.Y(n274));
   sky130_fd_sc_hs__nor2_1 U339 (.A(n2390),
	.B(n274),
	.Y(n277));
   sky130_fd_sc_hs__nand2_1 U340 (.A(commit_clk_cnt[5]),
	.B(n277),
	.Y(n276));
   sky130_fd_sc_hs__nor2_1 U341 (.A(n2370),
	.B(n276),
	.Y(n279));
   sky130_fd_sc_hs__nand2_1 U342 (.A(commit_clk_cnt[7]),
	.B(n279),
	.Y(n278));
   sky130_fd_sc_hs__nor2_1 U343 (.A(n2270),
	.B(n278),
	.Y(n281));
   sky130_fd_sc_hs__nand2_1 U344 (.A(commit_clk_cnt[9]),
	.B(n281),
	.Y(n280));
   sky130_fd_sc_hs__nor2_1 U345 (.A(n2320),
	.B(n280),
	.Y(n283));
   sky130_fd_sc_hs__nand2_1 U346 (.A(commit_clk_cnt[11]),
	.B(n283),
	.Y(n282));
   sky130_fd_sc_hs__nor2_1 U347 (.A(n2350),
	.B(n282),
	.Y(n285));
   sky130_fd_sc_hs__nand2_1 U348 (.A(commit_clk_cnt[13]),
	.B(n285),
	.Y(n284));
   sky130_fd_sc_hs__nor2_1 U349 (.A(n2330),
	.B(n284),
	.Y(n2870));
   sky130_fd_sc_hs__nand2_1 U350 (.A(commit_clk_cnt[15]),
	.B(n2870),
	.Y(n2860));
   sky130_fd_sc_hs__nor2_1 U351 (.A(n2250),
	.B(n2860),
	.Y(n2890));
   sky130_fd_sc_hs__a21oi_1 U352 (.A1(n2250),
	.A2(n2860),
	.B1(n2890),
	.Y(N87));
   sky130_fd_sc_hs__nor2b_1 U353 (.A(CurrentState_1_),
	.B_N(C19_DATA2_1),
	.Y(N287));
   sky130_fd_sc_hs__nand2_1 U359 (.A(commit_clk_cnt[17]),
	.B(n2890),
	.Y(n2880));
   sky130_fd_sc_hs__nor2_1 U360 (.A(n2340),
	.B(n2880),
	.Y(n2910));
   sky130_fd_sc_hs__nand2_1 U361 (.A(commit_clk_cnt[19]),
	.B(n2910),
	.Y(n2900));
   sky130_fd_sc_hs__nor2_1 U362 (.A(n2410),
	.B(n2900),
	.Y(n293));
   sky130_fd_sc_hs__nand2_1 U363 (.A(commit_clk_cnt[21]),
	.B(n293),
	.Y(n2920));
   sky130_fd_sc_hs__nor2_1 U364 (.A(n2310),
	.B(n2920),
	.Y(n295));
   sky130_fd_sc_hs__nand2_1 U365 (.A(commit_clk_cnt[23]),
	.B(n295),
	.Y(n2940));
   sky130_fd_sc_hs__nor2_1 U366 (.A(n2300),
	.B(n2940),
	.Y(n297));
   sky130_fd_sc_hs__nand2_1 U367 (.A(commit_clk_cnt[25]),
	.B(n297),
	.Y(n296));
   sky130_fd_sc_hs__nor2_1 U368 (.A(n2260),
	.B(n296),
	.Y(n299));
   sky130_fd_sc_hs__a21oi_1 U369 (.A1(n2260),
	.A2(n296),
	.B1(n299),
	.Y(N97));
   sky130_fd_sc_hs__nor2b_1 U371 (.A(CurrentState_1_),
	.B_N(C19_DATA2_4),
	.Y(N290));
   sky130_fd_sc_hs__nor2b_1 U372 (.A(CurrentState_1_),
	.B_N(C19_DATA2_6),
	.Y(N292));
   sky130_fd_sc_hs__nor2b_1 U373 (.A(CurrentState_1_),
	.B_N(C19_DATA2_0),
	.Y(N286));
   sky130_fd_sc_hs__nor2b_1 U374 (.A(CurrentState_1_),
	.B_N(C19_DATA2_5),
	.Y(N291));
   sky130_fd_sc_hs__nor2b_1 U375 (.A(CurrentState_1_),
	.B_N(C19_DATA2_3),
	.Y(N289));
   sky130_fd_sc_hs__a21oi_1 U376 (.A1(n2270),
	.A2(n278),
	.B1(n281),
	.Y(N79));
   sky130_fd_sc_hs__xor2_1 U377 (.A(osc_fine_con[7]),
	.B(DP_OP_67J1_123_9407_n25),
	.X(n2280));
   sky130_fd_sc_hs__xor2_1 U378 (.A(n2280),
	.B(DP_OP_67J1_123_9407_n2),
	.X(n2290));
   sky130_fd_sc_hs__or2_1 U379 (.A(CurrentState_1_),
	.B(n2290),
	.X(n592));
   sky130_fd_sc_hs__a21oi_1 U380 (.A1(n2300),
	.A2(n2940),
	.B1(n297),
	.Y(N95));
   sky130_fd_sc_hs__a21oi_1 U381 (.A1(n2310),
	.A2(n2920),
	.B1(n295),
	.Y(N93));
   sky130_fd_sc_hs__a21oi_1 U382 (.A1(n2320),
	.A2(n280),
	.B1(n283),
	.Y(N81));
   sky130_fd_sc_hs__a21oi_1 U383 (.A1(n2330),
	.A2(n284),
	.B1(n2870),
	.Y(N85));
   sky130_fd_sc_hs__a21oi_1 U384 (.A1(n2340),
	.A2(n2880),
	.B1(n2910),
	.Y(N89));
   sky130_fd_sc_hs__a21oi_1 U385 (.A1(n2350),
	.A2(n282),
	.B1(n285),
	.Y(N83));
   sky130_fd_sc_hs__nand2_1 U388 (.A(commit_clk_cnt[27]),
	.B(n299),
	.Y(n298));
   sky130_fd_sc_hs__nor2_1 U389 (.A(n2380),
	.B(n298),
	.Y(n301));
   sky130_fd_sc_hs__nand2_1 U390 (.A(commit_clk_cnt[29]),
	.B(n301),
	.Y(n300));
   sky130_fd_sc_hs__nor2_1 U391 (.A(n2360),
	.B(n300),
	.Y(n302));
   sky130_fd_sc_hs__a21oi_1 U392 (.A1(n2360),
	.A2(n300),
	.B1(n302),
	.Y(N101));
   sky130_fd_sc_hs__a21oi_1 U393 (.A1(n2370),
	.A2(n276),
	.B1(n279),
	.Y(N77));
   sky130_fd_sc_hs__a21oi_1 U394 (.A1(n2380),
	.A2(n298),
	.B1(n301),
	.Y(N99));
   sky130_fd_sc_hs__a21oi_1 U395 (.A1(n2390),
	.A2(n274),
	.B1(n277),
	.Y(N75));
   sky130_fd_sc_hs__a21oi_1 U396 (.A1(n2400),
	.A2(n273),
	.B1(n275),
	.Y(N73));
   sky130_fd_sc_hs__a21oi_1 U397 (.A1(n2410),
	.A2(n2900),
	.B1(n293),
	.Y(N91));
   sky130_fd_sc_hs__and2_2 U398 (.A(N222),
	.B(N221),
	.X(n582));
   sky130_fd_sc_hs__nand3_1 U399 (.A(n582),
	.B(N223),
	.C(N224),
	.Y(n2420));
   sky130_fd_sc_hs__nor2_1 U400 (.A(n2420),
	.B(n583),
	.Y(n584));
   sky130_fd_sc_hs__xnor2_1 U401 (.A(n535),
	.B(n2430),
	.Y(N209));
   sky130_fd_sc_hs__nand2_1 U402 (.A(N210),
	.B(N209),
	.Y(n574));
   sky130_fd_sc_hs__nor2_1 U404 (.A(n315),
	.B(n574),
	.Y(n575));
   sky130_fd_sc_hs__clkinv_2 U405 (.A(n568),
	.Y(n559));
   sky130_fd_sc_hs__nor2_1 U406 (.A(n477),
	.B(n2450),
	.Y(n2440));
   sky130_fd_sc_hs__xor2_1 U407 (.A(n507),
	.B(n2440),
	.X(N207));
   sky130_fd_sc_hs__xnor2_1 U408 (.A(n504),
	.B(n2450),
	.Y(N205));
   sky130_fd_sc_hs__nand2_1 U409 (.A(N206),
	.B(N205),
	.Y(n572));
   sky130_fd_sc_hs__nand2_1 U411 (.A(n2460),
	.B(n481),
	.Y(n2470));
   sky130_fd_sc_hs__nand3_1 U414 (.A(n2480),
	.B(n460),
	.C(n524),
	.Y(n2490));
   sky130_fd_sc_hs__xnor2_1 U415 (.A(n542),
	.B(n2490),
	.Y(N214));
   sky130_fd_sc_hs__inv_4 U416 (.A(N216),
	.Y(n322));
   sky130_fd_sc_hs__inv_4 U418 (.A(N215),
	.Y(n320));
   sky130_fd_sc_hs__nand2_1 U419 (.A(N214),
	.B(N213),
	.Y(n308));
   sky130_fd_sc_hs__nand2_1 U421 (.A(n252),
	.B(n2510),
	.Y(n253));
   sky130_fd_sc_hs__nor2_2 U422 (.A(n253),
	.B(n577),
	.Y(n578));
   sky130_fd_sc_hs__nand2_1 U423 (.A(N247),
	.B(N246),
	.Y(n254));
   sky130_fd_sc_hs__nor2b_1 U425 (.A(stat_error[0]),
	.B_N(n255),
	.Y(n256));
   sky130_fd_sc_hs__nor2_1 U426 (.A(n256),
	.B(n571),
	.Y(N202));
   sky130_fd_sc_hs__xnor2_1 U430 (.A(osc_clk_count[5]),
	.B(n270),
	.Y(n260));
   sky130_fd_sc_hs__nand2_2 U431 (.A(n259),
	.B(sync_flag),
	.Y(n263));
   sky130_fd_sc_hs__xnor2_1 U437 (.A(n454),
	.B(n494),
	.Y(N250));
   sky130_fd_sc_hs__xnor2_1 U438 (.A(n497),
	.B(n496),
	.Y(N248));
   sky130_fd_sc_hs__nand3_1 U439 (.A(n462),
	.B(n479),
	.C(n478),
	.Y(n265));
   sky130_fd_sc_hs__xnor2_1 U440 (.A(n509),
	.B(n265),
	.Y(N249));
   sky130_fd_sc_hs__nand3_1 U441 (.A(n266),
	.B(n459),
	.C(n501),
	.Y(n267));
   sky130_fd_sc_hs__xnor2_1 U442 (.A(n530),
	.B(n267),
	.Y(N226));
   sky130_fd_sc_hs__a21oi_1 U443 (.A1(n599),
	.A2(osc_clk_count[3]),
	.B1(osc_clk_count[4]),
	.Y(n269));
   sky130_fd_sc_hs__xor2_1 U446 (.A(fine_con_step_size[3]),
	.B(DP_OP_67J1_123_9407_n25),
	.X(DP_OP_67J1_123_9407_n13));
   sky130_fd_sc_hs__xor2_1 U447 (.A(fine_con_step_size[2]),
	.B(DP_OP_67J1_123_9407_n25),
	.X(DP_OP_67J1_123_9407_n14));
   sky130_fd_sc_hs__xor2_1 U448 (.A(fine_con_step_size[1]),
	.B(DP_OP_67J1_123_9407_n25),
	.X(DP_OP_67J1_123_9407_n15));
   sky130_fd_sc_hs__xor2_1 U449 (.A(fine_con_step_size[0]),
	.B(DP_OP_67J1_123_9407_n25),
	.X(DP_OP_67J1_123_9407_n16));
   sky130_fd_sc_hs__o21a_1 U451 (.A1(n272),
	.A2(stat_clean[0]),
	.B1(n303),
	.X(N227));
   sky130_fd_sc_hs__o21a_1 U452 (.A1(commit_clk_cnt[1]),
	.A2(commit_clk_cnt[0]),
	.B1(n273),
	.X(N72));
   sky130_fd_sc_hs__o21a_1 U453 (.A1(commit_clk_cnt[3]),
	.A2(n275),
	.B1(n274),
	.X(N74));
   sky130_fd_sc_hs__o21a_1 U454 (.A1(commit_clk_cnt[5]),
	.A2(n277),
	.B1(n276),
	.X(N76));
   sky130_fd_sc_hs__o21a_1 U455 (.A1(commit_clk_cnt[7]),
	.A2(n279),
	.B1(n278),
	.X(N78));
   sky130_fd_sc_hs__o21a_1 U456 (.A1(commit_clk_cnt[9]),
	.A2(n281),
	.B1(n280),
	.X(N80));
   sky130_fd_sc_hs__o21a_1 U457 (.A1(commit_clk_cnt[11]),
	.A2(n283),
	.B1(n282),
	.X(N82));
   sky130_fd_sc_hs__o21a_1 U458 (.A1(commit_clk_cnt[13]),
	.A2(n285),
	.B1(n284),
	.X(N84));
   sky130_fd_sc_hs__o21a_1 U459 (.A1(commit_clk_cnt[15]),
	.A2(n2870),
	.B1(n2860),
	.X(N86));
   sky130_fd_sc_hs__o21a_1 U460 (.A1(commit_clk_cnt[17]),
	.A2(n2890),
	.B1(n2880),
	.X(N88));
   sky130_fd_sc_hs__o21a_1 U461 (.A1(commit_clk_cnt[19]),
	.A2(n2910),
	.B1(n2900),
	.X(N90));
   sky130_fd_sc_hs__o21a_1 U462 (.A1(commit_clk_cnt[21]),
	.A2(n293),
	.B1(n2920),
	.X(N92));
   sky130_fd_sc_hs__o21a_1 U463 (.A1(commit_clk_cnt[23]),
	.A2(n295),
	.B1(n2940),
	.X(N94));
   sky130_fd_sc_hs__o21a_1 U464 (.A1(commit_clk_cnt[25]),
	.A2(n297),
	.B1(n296),
	.X(N96));
   sky130_fd_sc_hs__o21a_1 U465 (.A1(commit_clk_cnt[27]),
	.A2(n299),
	.B1(n298),
	.X(N98));
   sky130_fd_sc_hs__o21a_1 U466 (.A1(commit_clk_cnt[29]),
	.A2(n301),
	.B1(n300),
	.X(N100));
   sky130_fd_sc_hs__xor2_1 U467 (.A(commit_clk_cnt[31]),
	.B(n302),
	.X(N102));
   sky130_fd_sc_hs__xnor2_1 U468 (.A(stat_clean[1]),
	.B(n303),
	.Y(N228));
   sky130_fd_sc_hs__xnor2_1 U471 (.A(stat_clean[2]),
	.B(n305),
	.Y(N229));
   sky130_fd_sc_hs__nand2_1 U472 (.A(n307),
	.B(N230),
	.Y(n551));
   sky130_fd_sc_hs__nand2_1 U473 (.A(n307),
	.B(n306),
	.Y(n557));
   sky130_fd_sc_hs__nand2_1 U474 (.A(n568),
	.B(n561),
	.Y(n560));
   sky130_fd_sc_hs__nand2_1 U475 (.A(n568),
	.B(n565),
	.Y(n564));
   sky130_fd_sc_hs__and3_2 U476 (.A(n565),
	.B(N248),
	.C(N249),
	.X(n567));
   sky130_fd_sc_hs__nand2_1 U477 (.A(n568),
	.B(n567),
	.Y(n566));
   sky130_fd_sc_hs__xnor2_1 U479 (.A(n333),
	.B(n571),
	.Y(N203));
   sky130_fd_sc_hs__nand2_1 U480 (.A(n571),
	.B(stat_error[1]),
	.Y(n569));
   sky130_fd_sc_hs__and2_2 U481 (.A(n575),
	.B(N212),
	.X(n579));
   sky130_fd_sc_hs__inv_4 U482 (.A(n308),
	.Y(n309));
   sky130_fd_sc_hs__and2_2 U483 (.A(n579),
	.B(n309),
	.X(n576));
   sky130_fd_sc_hs__nor2_1 U486 (.A(n349),
	.B(N207),
	.Y(n366));
   sky130_fd_sc_hs__a21oi_1 U487 (.A1(N231),
	.A2(n338),
	.B1(n366),
	.Y(n372));
   sky130_fd_sc_hs__nor2_1 U489 (.A(N226),
	.B(n345),
	.Y(n420));
   sky130_fd_sc_hs__nor2_1 U490 (.A(N241),
	.B(n322),
	.Y(n365));
   sky130_fd_sc_hs__nor2_1 U491 (.A(n420),
	.B(n365),
	.Y(n314));
   sky130_fd_sc_hs__nor2_1 U496 (.A(N237),
	.B(n312),
	.Y(n390));
   sky130_fd_sc_hs__inv_4 U497 (.A(N217),
	.Y(n323));
   sky130_fd_sc_hs__nor2_1 U498 (.A(N242),
	.B(n323),
	.Y(n363));
   sky130_fd_sc_hs__nand2_1 U500 (.A(N237),
	.B(n312),
	.Y(n381));
   sky130_fd_sc_hs__nand4_1 U501 (.A(n372),
	.B(n314),
	.C(n313),
	.D(n381),
	.Y(n359));
   sky130_fd_sc_hs__inv_4 U502 (.A(N235),
	.Y(n316));
   sky130_fd_sc_hs__o2bb2a_1 U503 (.A1_N(N210),
	.A2_N(n316),
	.B1(N236),
	.B2(n315),
	.X(n387));
   sky130_fd_sc_hs__o21a_1 U506 (.A1(N211),
	.A2(n318),
	.B1(n389),
	.X(n382));
   sky130_fd_sc_hs__o2bb2a_1 U509 (.A1_N(N205),
	.A2_N(n334),
	.B1(n332),
	.B2(stat_clean[2]),
	.X(n367));
   sky130_fd_sc_hs__o2bb2a_1 U510 (.A1_N(stat_error[1]),
	.A2_N(n446),
	.B1(stat_clean[0]),
	.B2(n319),
	.X(n370));
   sky130_fd_sc_hs__nand4_1 U511 (.A(n387),
	.B(n382),
	.C(n367),
	.D(n370),
	.Y(n358));
   sky130_fd_sc_hs__o2bb2a_1 U513 (.A1_N(N214),
	.A2_N(n321),
	.B1(N240),
	.B2(n320),
	.X(n391));
   sky130_fd_sc_hs__inv_4 U514 (.A(N210),
	.Y(n325));
   sky130_fd_sc_hs__nor2_1 U515 (.A(N214),
	.B(n321),
	.Y(n392));
   sky130_fd_sc_hs__nand2_1 U516 (.A(N241),
	.B(n322),
	.Y(n324));
   sky130_fd_sc_hs__nand2_1 U517 (.A(N242),
	.B(n323),
	.Y(n364));
   sky130_fd_sc_hs__o211ai_1 U518 (.A1(N215),
	.A2(n585),
	.B1(n324),
	.C1(n364),
	.Y(n394));
   sky130_fd_sc_hs__a211oi_1 U519 (.A1(N235),
	.A2(n325),
	.B1(n392),
	.C1(n394),
	.Y(n397));
   sky130_fd_sc_hs__nand2b_1 U523 (.A_N(N225),
	.B(N250),
	.Y(n360));
   sky130_fd_sc_hs__nand2_1 U525 (.A(n347),
	.B(N249),
	.Y(n327));
   sky130_fd_sc_hs__inv_4 U528 (.A(N223),
	.Y(n344));
   sky130_fd_sc_hs__nand2_1 U529 (.A(N248),
	.B(n344),
	.Y(n402));
   sky130_fd_sc_hs__a21oi_1 U534 (.A1(N243),
	.A2(n341),
	.B1(n410),
	.Y(n331));
   sky130_fd_sc_hs__nand2_1 U536 (.A(N245),
	.B(n337),
	.Y(n404));
   sky130_fd_sc_hs__nand3b_1 U537 (.A_N(n414),
	.B(n331),
	.C(n404),
	.Y(n398));
   sky130_fd_sc_hs__a22oi_1 U538 (.A1(stat_clean[1]),
	.A2(n333),
	.B1(stat_clean[2]),
	.B2(n332),
	.Y(n336));
   sky130_fd_sc_hs__nor2_1 U539 (.A(N205),
	.B(n334),
	.Y(n368));
   sky130_fd_sc_hs__nor3_1 U542 (.A(n362),
	.B(n398),
	.C(n369),
	.Y(n356));
   sky130_fd_sc_hs__and2_2 U544 (.A(n340),
	.B(N208),
	.X(n379));
   sky130_fd_sc_hs__nor2_1 U545 (.A(N245),
	.B(n337),
	.Y(n405));
   sky130_fd_sc_hs__nand2_1 U547 (.A(N244),
	.B(n342),
	.Y(n418));
   sky130_fd_sc_hs__nand2_1 U549 (.A(N209),
	.B(n339),
	.Y(n383));
   sky130_fd_sc_hs__nand3b_1 U550 (.A_N(n405),
	.B(n418),
	.C(n383),
	.Y(n354));
   sky130_fd_sc_hs__nor2_1 U551 (.A(N231),
	.B(n338),
	.Y(n374));
   sky130_fd_sc_hs__nor2_1 U552 (.A(N209),
	.B(n339),
	.Y(n378));
   sky130_fd_sc_hs__nor2_1 U553 (.A(N208),
	.B(n340),
	.Y(n375));
   sky130_fd_sc_hs__nor3_1 U554 (.A(n374),
	.B(n378),
	.C(n375),
	.Y(n352));
   sky130_fd_sc_hs__nor2_1 U555 (.A(N243),
	.B(n341),
	.Y(n407));
   sky130_fd_sc_hs__nor2_1 U556 (.A(N244),
	.B(n342),
	.Y(n406));
   sky130_fd_sc_hs__nor2_1 U559 (.A(N248),
	.B(n344),
	.Y(n401));
   sky130_fd_sc_hs__nor4_1 U560 (.A(n407),
	.B(n406),
	.C(n403),
	.D(n401),
	.Y(n351));
   sky130_fd_sc_hs__nand2_1 U561 (.A(N226),
	.B(n345),
	.Y(n421));
   sky130_fd_sc_hs__nor2_1 U564 (.A(stat_error[0]),
	.B(n447),
	.Y(n348));
   sky130_fd_sc_hs__nor2_1 U565 (.A(N249),
	.B(n347),
	.Y(n361));
   sky130_fd_sc_hs__nor4b_1 U566 (.A(n412),
	.B(n348),
	.C(n361),
	.D_N(n421),
	.Y(n350));
   sky130_fd_sc_hs__nand2_1 U567 (.A(N207),
	.B(n349),
	.Y(n376));
   sky130_fd_sc_hs__nand4_1 U568 (.A(n352),
	.B(n351),
	.C(n350),
	.D(n376),
	.Y(n353));
   sky130_fd_sc_hs__nor3_1 U569 (.A(n379),
	.B(n354),
	.C(n353),
	.Y(n355));
   sky130_fd_sc_hs__nand4_1 U570 (.A(n391),
	.B(n397),
	.C(n356),
	.D(n355),
	.Y(n357));
   sky130_fd_sc_hs__nor3_1 U571 (.A(n359),
	.B(n358),
	.C(n357),
	.Y(n590));
   sky130_fd_sc_hs__o21ai_1 U572 (.A1(n362),
	.A2(n361),
	.B1(n360),
	.Y(n423));
   sky130_fd_sc_hs__a21oi_1 U573 (.A1(n365),
	.A2(n364),
	.B1(n363),
	.Y(n400));
   sky130_fd_sc_hs__o22ai_1 U575 (.A1(n370),
	.A2(n369),
	.B1(n368),
	.B2(n367),
	.Y(n371));
   sky130_fd_sc_hs__a22oi_1 U576 (.A1(n374),
	.A2(n373),
	.B1(n372),
	.B2(n371),
	.Y(n377));
   sky130_fd_sc_hs__a21oi_1 U577 (.A1(n377),
	.A2(n376),
	.B1(n375),
	.Y(n380));
   sky130_fd_sc_hs__o21bai_1 U578 (.A1(n380),
	.A2(n379),
	.B1_N(n378),
	.Y(n384));
   sky130_fd_sc_hs__nand2_1 U579 (.A(n382),
	.B(n381),
	.Y(n386));
   sky130_fd_sc_hs__a21oi_1 U580 (.A1(n384),
	.A2(n383),
	.B1(n386),
	.Y(n396));
   sky130_fd_sc_hs__o21ai_1 U581 (.A1(n387),
	.A2(n386),
	.B1(n385),
	.Y(n388));
   sky130_fd_sc_hs__a21oi_1 U582 (.A1(n390),
	.A2(n389),
	.B1(n388),
	.Y(n393));
   sky130_fd_sc_hs__a21oi_1 U584 (.A1(n397),
	.A2(n396),
	.B1(n395),
	.Y(n399));
   sky130_fd_sc_hs__a21oi_1 U585 (.A1(n400),
	.A2(n399),
	.B1(n398),
	.Y(n419));
   sky130_fd_sc_hs__a21oi_1 U586 (.A1(n403),
	.A2(n402),
	.B1(n401),
	.Y(n416));
   sky130_fd_sc_hs__a211oi_1 U588 (.A1(n407),
	.A2(n418),
	.B1(n406),
	.C1(n405),
	.Y(n408));
   sky130_fd_sc_hs__o21bai_1 U590 (.A1(n412),
	.A2(n411),
	.B1_N(n410),
	.Y(n413));
   sky130_fd_sc_hs__o22ai_1 U591 (.A1(n416),
	.A2(n415),
	.B1(n414),
	.B2(n413),
	.Y(n417));
   sky130_fd_sc_hs__a21oi_1 U592 (.A1(n419),
	.A2(n418),
	.B1(n417),
	.Y(n422));
   sky130_fd_sc_hs__a31oi_1 U593 (.A1(n423),
	.A2(n422),
	.A3(n421),
	.B1(n420),
	.Y(n591));
   sky130_fd_sc_hs__and2_2 U594 (.A(aux_clk_out),
	.B(n424),
	.X(esample_N2));
   sky130_fd_sc_hs__nand2_1 U595 (.A(CurrentState_1_),
	.B(n960),
	.Y(N294));
   sky130_fd_sc_hs__a32oi_1 U596 (.A1(fine_control_avg_window_select[2]),
	.A2(n427),
	.A3(n426),
	.B1(n425),
	.B2(fine_control_avg_window_select[1]),
	.Y(n445));
   sky130_fd_sc_hs__a32oi_1 U597 (.A1(n431),
	.A2(n430),
	.A3(n429),
	.B1(n428),
	.B2(n430),
	.Y(n443));
   sky130_fd_sc_hs__nor2_1 U598 (.A(fine_control_avg_window_select[1]),
	.B(fine_control_avg_window_select[2]),
	.Y(n442));
   sky130_fd_sc_hs__a22oi_1 U599 (.A1(commit_clk_cnt[16]),
	.A2(n433),
	.B1(commit_clk_cnt[8]),
	.B2(n432),
	.Y(n440));
   sky130_fd_sc_hs__o21ai_1 U600 (.A1(n434),
	.A2(n436),
	.B1(commit_clk_cnt[24]),
	.Y(n438));
   sky130_fd_sc_hs__a21oi_1 U601 (.A1(commit_clk_cnt[1]),
	.A2(n436),
	.B1(n435),
	.Y(n437));
   sky130_fd_sc_hs__a32oi_1 U602 (.A1(n440),
	.A2(n439),
	.A3(n438),
	.B1(n437),
	.B2(fine_control_avg_window_select[0]),
	.Y(n441));
   sky130_fd_sc_hs__a22oi_1 U603 (.A1(fine_control_avg_window_select[0]),
	.A2(n443),
	.B1(n442),
	.B2(n441),
	.Y(n444));
   sky130_fd_sc_hs__o21ai_1 U604 (.A1(fine_control_avg_window_select[0]),
	.A2(n445),
	.B1(n444),
	.Y(commit_clk));
   sky130_fd_sc_hs__a21oi_1 U317 (.A1(n439),
	.A2(n2200),
	.B1(n2190),
	.Y(n2210));
   sky130_fd_sc_hs__dfsbp_2 CurrentState_reg_0_ (.CLK(commit_clk),
	.D(NextState[0]),
	.Q_N(n960),
	.SET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_2_ (.CLK(accumu_select),
	.D(N73),
	.Q(commit_clk_cnt[2]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_10_ (.CLK(FE_OFN2_accumu_select),
	.D(N81),
	.Q(commit_clk_cnt[10]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_14_ (.CLK(FE_OFN2_accumu_select),
	.D(N85),
	.Q(commit_clk_cnt[14]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_30_ (.CLK(FE_OFN2_accumu_select),
	.D(N101),
	.Q(commit_clk_cnt[30]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_28_ (.CLK(accumu_select),
	.D(N99),
	.Q(commit_clk_cnt[28]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_26_ (.CLK(accumu_select),
	.D(N97),
	.Q(commit_clk_cnt[26]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_18_ (.CLK(FE_OFN2_accumu_select),
	.D(N89),
	.Q(commit_clk_cnt[18]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_12_ (.CLK(FE_OFN2_accumu_select),
	.D(N83),
	.Q(commit_clk_cnt[12]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_6_ (.CLK(FE_OFN2_accumu_select),
	.D(N77),
	.Q(commit_clk_cnt[6]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_4_ (.CLK(accumu_select),
	.D(N75),
	.Q(commit_clk_cnt[4]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_22_ (.CLK(FE_OFN2_accumu_select),
	.D(N93),
	.Q(commit_clk_cnt[22]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_9_ (.CLK(FE_OFN2_accumu_select),
	.D(N80),
	.Q(commit_clk_cnt[9]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_31_ (.CLK(accumu_select),
	.D(N102),
	.Q(commit_clk_cnt[31]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_20_ (.CLK(FE_OFN2_accumu_select),
	.D(N91),
	.Q(commit_clk_cnt[20]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_19_ (.CLK(FE_OFN2_accumu_select),
	.D(N90),
	.Q(commit_clk_cnt[19]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_3_ (.CLK(accumu_select),
	.D(N74),
	.Q(commit_clk_cnt[3]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_0_ (.CLK(accumu_select),
	.D(n588),
	.Q(commit_clk_cnt[0]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_29_ (.CLK(accumu_select),
	.D(N100),
	.Q(commit_clk_cnt[29]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_11_ (.CLK(FE_OFN2_accumu_select),
	.D(N82),
	.Q(commit_clk_cnt[11]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_23_ (.CLK(accumu_select),
	.D(N94),
	.Q(commit_clk_cnt[23]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_13_ (.CLK(FE_OFN2_accumu_select),
	.D(N84),
	.Q(commit_clk_cnt[13]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_15_ (.CLK(FE_OFN2_accumu_select),
	.D(N86),
	.Q(commit_clk_cnt[15]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_17_ (.CLK(FE_OFN2_accumu_select),
	.D(N88),
	.Q(commit_clk_cnt[17]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_27_ (.CLK(accumu_select),
	.D(N98),
	.Q(commit_clk_cnt[27]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_7_ (.CLK(FE_OFN2_accumu_select),
	.D(N78),
	.Q(commit_clk_cnt[7]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_21_ (.CLK(FE_OFN2_accumu_select),
	.D(N92),
	.Q(commit_clk_cnt[21]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_1_ (.CLK(accumu_select),
	.D(N72),
	.Q(commit_clk_cnt[1]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_8_ (.CLK(FE_OFN2_accumu_select),
	.D(N79),
	.Q(commit_clk_cnt[8]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_24_ (.CLK(accumu_select),
	.D(N95),
	.Q(commit_clk_cnt[24]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_5_ (.CLK(accumu_select),
	.D(N76),
	.Q(commit_clk_cnt[5]),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_25_ (.CLK(accumu_select),
	.D(N96),
	.Q(commit_clk_cnt[25]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 commit_clk_cnt_reg_16_ (.CLK(FE_OFN2_accumu_select),
	.D(N87),
	.Q(commit_clk_cnt[16]),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 osc_fine_con_reg_7_ (.CLK(net804),
	.D(n592),
	.Q(osc_fine_con[7]),
	.SET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfstp_2 CurrentState_reg_1_ (.CLK(commit_clk),
	.D(NextState[1]),
	.Q(CurrentState_1_),
	.SET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfstp_2 R_37 (.CLK(n484),
	.D(N215),
	.Q(n525),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_156 (.CLK(ref_clk),
	.D(N248),
	.Q(n479),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_158 (.CLK(n484),
	.D(n572),
	.Q(n477),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_112 (.CLK(ref_clk),
	.D(N248),
	.Q(n497),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_198 (.CLK(n484),
	.D(n576),
	.Q(n455),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_203 (.CLK(ref_clk),
	.D(N238),
	.Q(n450),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_166 (.CLK(ref_clk),
	.D(n563),
	.Q(n472),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_136 (.CLK(ref_clk),
	.D(n555),
	.Q(n488),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_170 (.CLK(ref_clk),
	.D(n554),
	.Q(n470),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_91 (.CLK(n484),
	.D(N205),
	.Q(n504),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_69 (.CLK(n484),
	.D(n577),
	.Q(n513),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_6 (.CLK(n484),
	.D(N213),
	.Q(n540),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_200 (.CLK(ref_clk),
	.D(N244),
	.Q(n453),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_193 (.CLK(n484),
	.D(n579),
	.Q(n460),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 accumu_select_reg (.CLK(clk_out),
	.D(ref_clk),
	.Q(accumu_select),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__inv_4 U253 (.A(n349),
	.Y(N232));
   sky130_fd_sc_hs__inv_4 U177 (.A(n563),
	.Y(n562));
   sky130_fd_sc_hs__inv_4 U304 (.A(n436),
	.Y(n2090));
   sky130_fd_sc_hs__inv_4 U256 (.A(N240),
	.Y(n585));
   sky130_fd_sc_hs__inv_4 U546 (.A(N219),
	.Y(n342));
   sky130_fd_sc_hs__inv_4 U403 (.A(N211),
	.Y(n315));
   sky130_fd_sc_hs__inv_4 U185 (.A(N236),
	.Y(n318));
   sky130_fd_sc_hs__inv_4 U260 (.A(n2480),
	.Y(n2430));
   sky130_fd_sc_hs__dfxtp_2 out_star_reg (.CLK(clk_out),
	.D(n6),
	.Q(out_star));
   sky130_fd_sc_hs__dfxtp_1 osc_clk_count_reg_5_ (.CLK(net793),
	.D(n8),
	.Q(osc_clk_count[5]));
   sky130_fd_sc_hs__dfxtp_2 osc_clk_count_reg_2_ (.CLK(net793),
	.D(n11),
	.Q(osc_clk_count[2]));
   sky130_fd_sc_hs__dfxtp_4 sync_flag_reg (.CLK(ref_clk),
	.D(FE_RN_6_0),
	.Q(sync_flag));
   sky130_fd_sc_hs__dfstp_2 NextState_reg_0_ (.CLK(commit_clk),
	.D(n591),
	.Q(NextState[0]),
	.SET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfstp_2 NextState_reg_1_ (.CLK(commit_clk),
	.D(n590),
	.Q(NextState[1]),
	.SET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_5_ (.CLK(net804),
	.D(N291),
	.Q(osc_fine_con[5]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_6_ (.CLK(net804),
	.D(N292),
	.Q(osc_fine_con[6]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_3_ (.CLK(net804),
	.D(N289),
	.Q(osc_fine_con[3]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_4_ (.CLK(net804),
	.D(N290),
	.Q(osc_fine_con[4]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_0_ (.CLK(net804),
	.D(N286),
	.Q(osc_fine_con[0]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_1_ (.CLK(net804),
	.D(N287),
	.Q(osc_fine_con[1]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfrtp_4 osc_fine_con_reg_2_ (.CLK(net804),
	.D(N288),
	.Q(osc_fine_con[2]),
	.RESET_B(FE_RN_6_0));
   sky130_fd_sc_hs__dfstp_2 R_95 (.CLK(n484),
	.D(N219),
	.Q(n503),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_138 (.CLK(ref_clk),
	.D(n556),
	.Q(n487),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_34 (.CLK(n484),
	.D(n574),
	.Q(n526),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_63_RW_0 (.CLK(n484),
	.D(n575),
	.Q(n516),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_106 (.CLK(n484),
	.D(N223),
	.Q(n500),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_101_RW_0 (.CLK(n484),
	.D(N225),
	.Q(n501),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_97 (.CLK(ref_clk),
	.D(n556),
	.Q(n502),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_147_RW_0 (.CLK(n484),
	.D(n573),
	.Q(n481),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_153 (.CLK(ref_clk),
	.D(n567),
	.Q(n480),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_90_RW_0 (.CLK(n484),
	.D(N221),
	.Q(n505),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_157 (.CLK(ref_clk),
	.D(n565),
	.Q(n478),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_123_RW_0 (.CLK(n484),
	.D(N217),
	.Q(n492),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_60 (.CLK(n484),
	.D(N221),
	.Q(n517),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_84 (.CLK(n484),
	.D(N207),
	.Q(n507),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_50 (.CLK(ref_clk),
	.D(N237),
	.Q(n519),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_20 (.CLK(n484),
	.D(N222),
	.Q(n533),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_8 (.CLK(n484),
	.D(N210),
	.Q(n539),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_46 (.CLK(n484),
	.D(N208),
	.Q(n521),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_82 (.CLK(ref_clk),
	.D(N251),
	.Q(n508),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_30 (.CLK(n484),
	.D(N225),
	.Q(n528),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_76 (.CLK(n484),
	.D(N217),
	.Q(n511),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_42 (.CLK(ref_clk),
	.D(N239),
	.Q(n523),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_14 (.CLK(n484),
	.D(N211),
	.Q(n536),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_74 (.CLK(n484),
	.D(N219),
	.Q(n512),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_24 (.CLK(n484),
	.D(N223),
	.Q(n531),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_4 (.CLK(n484),
	.D(N216),
	.Q(n541),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_53_RW_0 (.CLK(n484),
	.D(N209),
	.Q(n518),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_80 (.CLK(ref_clk),
	.D(N249),
	.Q(n509),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_32 (.CLK(ref_clk),
	.D(N241),
	.Q(n527),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_196 (.CLK(n484),
	.D(n581),
	.Q(n457),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_16 (.CLK(n484),
	.D(N209),
	.Q(n535),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_12 (.CLK(n484),
	.D(N215),
	.Q(n537),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_28 (.CLK(n484),
	.D(N218),
	.Q(n529),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_22 (.CLK(n484),
	.D(N220),
	.Q(n532),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_10 (.CLK(n484),
	.D(N212),
	.Q(n538),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_26 (.CLK(n484),
	.D(N226),
	.Q(n530),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_197 (.CLK(n484),
	.D(n580),
	.Q(n456),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_195 (.CLK(n484),
	.D(n582),
	.Q(n458),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_2 (.CLK(n484),
	.D(N214),
	.Q(n542),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_194 (.CLK(n484),
	.D(n584),
	.Q(n459),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_18 (.CLK(n484),
	.D(N224),
	.Q(n534),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_143 (.CLK(n484),
	.D(n569),
	.Q(n483),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_199 (.CLK(ref_clk),
	.D(N250),
	.Q(n454),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_139 (.CLK(n484),
	.D(n583),
	.Q(n486),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_168 (.CLK(ref_clk),
	.D(N246),
	.Q(n471),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_175 (.CLK(n484),
	.D(n570),
	.Q(n466),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_161 (.CLK(ref_clk),
	.D(n561),
	.Q(n476),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_41_RW_0 (.CLK(n484),
	.D(N213),
	.Q(n524),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_124 (.CLK(ref_clk),
	.D(n585),
	.Q(n491),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_179 (.CLK(ref_clk),
	.D(n562),
	.Q(n465),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_78 (.CLK(ref_clk),
	.D(N245),
	.Q(n510),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_165 (.CLK(ref_clk),
	.D(n551),
	.Q(n473),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_64 (.CLK(ref_clk),
	.D(N240),
	.Q(n515),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_86 (.CLK(ref_clk),
	.D(N247),
	.Q(n506),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_48 (.CLK(ref_clk),
	.D(N235),
	.Q(n520),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_114 (.CLK(ref_clk),
	.D(N243),
	.Q(n495),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_108 (.CLK(ref_clk),
	.D(N246),
	.Q(n499),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_132 (.CLK(ref_clk),
	.D(n559),
	.Q(n490),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_202 (.CLK(ref_clk),
	.D(n558),
	.Q(n451),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_173 (.CLK(ref_clk),
	.D(n552),
	.Q(n468),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_201 (.CLK(ref_clk),
	.D(N242),
	.Q(n452),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_181 (.CLK(n484),
	.D(n578),
	.Q(n464),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_192 (.CLK(ref_clk),
	.D(n557),
	.Q(n461),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfxtp_1 R_0 (.CLK(net793),
	.D(n10),
	.Q(osc_clk_count[3]));
   sky130_fd_sc_hs__dfxtp_2 osc_clk_count_reg_0_ (.CLK(net793),
	.D(n13),
	.Q(osc_clk_count[0]));
   sky130_fd_sc_hs__dfxtp_4 R_1 (.CLK(net793),
	.D(n543),
	.Q(n586));
   sky130_fd_sc_hs__dfxtp_4 osc_clk_count_reg_4_ (.CLK(net793),
	.D(n9),
	.Q(osc_clk_count[4]));
   sky130_fd_sc_hs__dfxtp_2 osc_clk_count_reg_1_ (.CLK(net793),
	.D(n12),
	.Q(osc_clk_count[1]));
   sky130_fd_sc_hs__dfstp_2 R_113 (.CLK(ref_clk),
	.D(n564),
	.Q(n496),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_117 (.CLK(ref_clk),
	.D(n566),
	.Q(n494),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_189 (.CLK(ref_clk),
	.D(n553),
	.Q(n463),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_111 (.CLK(ref_clk),
	.D(n560),
	.Q(n498),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfstp_2 R_191 (.CLK(ref_clk),
	.D(n568),
	.Q(n462),
	.SET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__clkinv_2 U152 (.A(div_ratio_half[4]),
	.Y(n143));
   sky130_fd_sc_hs__inv_16 U436 (.A(ref_clk),
	.Y(n484));
   sky130_fd_sc_hs__inv_4 U278 (.A(fine_control_avg_window_select[0]),
	.Y(n439));
   sky130_fd_sc_hs__inv_4 U290 (.A(fine_control_avg_window_select[1]),
	.Y(n427));
   sky130_fd_sc_hs__clkinv_2 U146 (.A(n134),
	.Y(n135));
   sky130_fd_sc_hs__nand2_4 U129 (.A(n134),
	.B(n129),
	.Y(n137));
   sky130_fd_sc_hs__xnor2_2 U166 (.A(n469),
	.B(n468),
	.Y(N230));
   sky130_fd_sc_hs__xnor2_2 U165 (.A(n474),
	.B(n473),
	.Y(N231));
   sky130_fd_sc_hs__nand2_1 U195 (.A(n463),
	.B(n448),
	.Y(n159));
   sky130_fd_sc_hs__inv_4 U178 (.A(n475),
	.Y(n157));
   sky130_fd_sc_hs__inv_4 U210 (.A(stat_error[0]),
	.Y(n319));
   sky130_fd_sc_hs__inv_4 U478 (.A(stat_error[1]),
	.Y(n333));
   sky130_fd_sc_hs__clkinv_2 U144 (.A(osc_clk_count[0]),
	.Y(n133));
   sky130_fd_sc_hs__clkinv_2 U507 (.A(N230),
	.Y(n334));
   sky130_fd_sc_hs__nand2_4 U133 (.A(n586),
	.B(div_ratio_half[3]),
	.Y(n136));
   sky130_fd_sc_hs__nand2_2 U167 (.A(N231),
	.B(N230),
	.Y(n162));
   sky130_fd_sc_hs__inv_4 U548 (.A(N234),
	.Y(n339));
   sky130_fd_sc_hs__inv_4 U331 (.A(commit_clk_cnt[12]),
	.Y(n2350));
   sky130_fd_sc_hs__inv_4 U330 (.A(commit_clk_cnt[14]),
	.Y(n2330));
   sky130_fd_sc_hs__inv_4 U335 (.A(commit_clk_cnt[4]),
	.Y(n2390));
   sky130_fd_sc_hs__inv_4 U303 (.A(commit_clk_cnt[2]),
	.Y(n2400));
   sky130_fd_sc_hs__inv_4 U332 (.A(commit_clk_cnt[10]),
	.Y(n2320));
   sky130_fd_sc_hs__inv_4 U329 (.A(commit_clk_cnt[16]),
	.Y(n2250));
   sky130_fd_sc_hs__inv_4 U334 (.A(commit_clk_cnt[6]),
	.Y(n2370));
   sky130_fd_sc_hs__inv_4 U333 (.A(commit_clk_cnt[8]),
	.Y(n2270));
   sky130_fd_sc_hs__inv_4 U354 (.A(commit_clk_cnt[26]),
	.Y(n2260));
   sky130_fd_sc_hs__inv_4 U355 (.A(commit_clk_cnt[24]),
	.Y(n2300));
   sky130_fd_sc_hs__inv_4 U356 (.A(commit_clk_cnt[22]),
	.Y(n2310));
   sky130_fd_sc_hs__inv_4 U357 (.A(commit_clk_cnt[20]),
	.Y(n2410));
   sky130_fd_sc_hs__inv_4 U358 (.A(commit_clk_cnt[18]),
	.Y(n2340));
   sky130_fd_sc_hs__inv_4 U370 (.A(commit_clk_cnt[0]),
	.Y(n588));
   sky130_fd_sc_hs__inv_4 U386 (.A(commit_clk_cnt[30]),
	.Y(n2360));
   sky130_fd_sc_hs__inv_4 U387 (.A(commit_clk_cnt[28]),
	.Y(n2380));
   sky130_fd_sc_hs__inv_4 U543 (.A(N233),
	.Y(n340));
   sky130_fd_sc_hs__inv_4 U488 (.A(N251),
	.Y(n345));
   sky130_fd_sc_hs__inv_4 U508 (.A(N204),
	.Y(n332));
   sky130_fd_sc_hs__nand2_1 U298 (.A(n2050),
	.B(n2040),
	.Y(n426));
   sky130_fd_sc_hs__inv_4 U301 (.A(n429),
	.Y(n2060));
   sky130_fd_sc_hs__nand2b_2 U160 (.A_N(esample_DR),
	.B(esample_DF),
	.Y(n424));
   sky130_fd_sc_hs__inv_4 U512 (.A(N239),
	.Y(n321));
   sky130_fd_sc_hs__clkinv_2 U208 (.A(n424),
	.Y(n168));
   sky130_fd_sc_hs__nand3_1 U135 (.A(n124),
	.B(n125),
	.C(FE_PSN1_n136),
	.Y(n150));
   sky130_fd_sc_hs__nand2_4 U209 (.A(accumu_select),
	.B(n168),
	.Y(n255));
   sky130_fd_sc_hs__nand2_2 U162 (.A(n272),
	.B(stat_clean[0]),
	.Y(n303));
   sky130_fd_sc_hs__inv_4 U531 (.A(N218),
	.Y(n341));
   sky130_fd_sc_hs__nor2_2 U151 (.A(n142),
	.B(n141),
	.Y(n149));
   sky130_fd_sc_hs__inv_4 U524 (.A(N224),
	.Y(n347));
   sky130_fd_sc_hs__inv_4 U485 (.A(N206),
	.Y(n338));
   sky130_fd_sc_hs__inv_4 U535 (.A(N220),
	.Y(n337));
   sky130_fd_sc_hs__inv_4 U495 (.A(N212),
	.Y(n312));
   sky130_fd_sc_hs__inv_4 U574 (.A(n366),
	.Y(n373));
   sky130_fd_sc_hs__nor2_2 U163 (.A(n164),
	.B(n303),
	.Y(n307));
   sky130_fd_sc_hs__nor3_2 U420 (.A(n320),
	.B(n319),
	.C(n308),
	.Y(n2510));
   sky130_fd_sc_hs__nand3_1 U194 (.A(n556),
	.B(N239),
	.C(N238),
	.Y(n558));
   sky130_fd_sc_hs__nand2_2 U413 (.A(n573),
	.B(N208),
	.Y(n577));
   sky130_fd_sc_hs__nand2_1 U526 (.A(n360),
	.B(n327),
	.Y(n415));
   sky130_fd_sc_hs__inv_4 U213 (.A(n960),
	.Y(n169));
   sky130_fd_sc_hs__dfrtp_4 R_142 (.CLK(n484),
	.D(N204),
	.Q(n485),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_44 (.CLK(n484),
	.D(N206),
	.Q(n522),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfstp_2 R_145_RW_0 (.CLK(n484),
	.D(N205),
	.Q(n482),
	.SET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_172 (.CLK(ref_clk),
	.D(N230),
	.Q(n469),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_66 (.CLK(ref_clk),
	.D(N236),
	.Q(n514),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_120 (.CLK(ref_clk),
	.D(N233),
	.Q(n493),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_134 (.CLK(ref_clk),
	.D(n553),
	.Q(n489),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrbp_1 stat_clean_reg_0_ (.CLK(ref_clk),
	.D(N227),
	.Q(stat_clean[0]),
	.Q_N(n447),
	.RESET_B(FE_OFN0_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_164 (.CLK(ref_clk),
	.D(N231),
	.Q(n474),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_163 (.CLK(ref_clk),
	.D(n557),
	.Q(n475),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_204 (.CLK(ref_clk),
	.D(N234),
	.Q(n449),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__dfrtp_4 R_205 (.CLK(ref_clk),
	.D(N232),
	.Q(n448),
	.RESET_B(FE_OFN1_n2210));
   sky130_fd_sc_hs__nor2_4 U127 (.A(div_ratio_half[0]),
	.B(div_ratio_half[1]),
	.Y(n134));
   sky130_fd_sc_hs__inv_4 U128 (.A(div_ratio_half[2]),
	.Y(n129));
   sky130_fd_sc_hs__nand2_1 U159 (.A(stat_clean[2]),
	.B(stat_clean[1]),
	.Y(n164));
   sky130_fd_sc_hs__clkinv_2 U252 (.A(out_star),
	.Y(esample_osc_out_star_b));
   sky130_fd_sc_hs__xnor2_2 U241 (.A(n485),
	.B(n483),
	.Y(N204));
   sky130_fd_sc_hs__xnor2_2 U191 (.A(n523),
	.B(n156),
	.Y(N239));
   sky130_fd_sc_hs__inv_2 U131 (.A(n122),
	.Y(n146));
   sky130_fd_sc_hs__xnor2_2 U193 (.A(n450),
	.B(n158),
	.Y(N238));
   sky130_fd_sc_hs__nor2_4 U161 (.A(n424),
	.B(accumu_select),
	.Y(n272));
   sky130_fd_sc_hs__xnor2_2 U412 (.A(n521),
	.B(n2470),
	.Y(N208));
   sky130_fd_sc_hs__nor2_4 U424 (.A(n254),
	.B(n563),
	.Y(n565));
   sky130_fd_sc_hs__nor2_4 U211 (.A(n255),
	.B(n319),
	.Y(n571));
   sky130_fd_sc_hs__nor2b_1 U410 (.A(n572),
	.B_N(N207),
	.Y(n573));
   sky130_fd_sc_hs__inv_4 U164 (.A(n307),
	.Y(n552));
   sky130_fd_sc_hs__nor2_4 U207 (.A(n167),
	.B(n558),
	.Y(n568));
   sky130_fd_sc_hs__nor2_1 U168 (.A(n162),
	.B(n552),
	.Y(n553));
   sky130_fd_sc_hs__nor2b_1 U8 (.A(rst),
	.B_N(FE_OCPN3_n259),
	.Y(n6));
   sky130_fd_sc_hs__o32ai_1 U583 (.A1(n394),
	.A2(n393),
	.A3(n392),
	.B1(n391),
	.B2(n394),
	.Y(n395));
   sky130_fd_sc_hs__and2_2 U270 (.A(n191),
	.B(osc_clk_count[2]),
	.X(n599));
endmodule

