# Adapted from Garnet and ButterPHY

name: qtm

commands:
  - |
    mkdir -p build
    mkdir -p outputs
    cd build

    # build prbs_generator_syn QTM
    mkdir -p prbs_generator_syn
    cd prbs_generator_syn
    pt_shell -f ../../prbs_generator_syn.qtm.tcl
    cd ..

    # build hr_16t4_mux_top QTM
    mkdir -p hr_16t4_mux_top
    cd hr_16t4_mux_top
    pt_shell -f ../../hr_16t4_mux_top.qtm.tcl
    cd ..

    # build qr_4t1_mux_top QTM
    mkdir -p qr_4t1_mux_top
    cd qr_4t1_mux_top
    pt_shell -f ../../qr_4t1_mux_top.qtm.tcl
    cd ..

    # link build products into output folder
    # cd ../outputs
    # ln -s ../build/analog_core/analog_core_lib.db analog_core_lib.db
    # ln -s ../build/analog_core/analog_core.lib analog_core.lib
    # ln -s ../build/input_buffer/input_buffer_lib.db input_buffer_lib.db
    # ln -s ../build/input_buffer/input_buffer.lib input_buffer.lib
    # ln -s ../build/output_buffer/output_buffer_lib.db output_buffer_lib.db
    # ln -s ../build/output_buffer/output_buffer.lib output_buffer.lib
    # ln -s ../build/mdll_r1_top/mdll_r1_top_lib.db mdll_r1_top_lib.db
    # ln -s ../build/mdll_r1_top/mdll_r1_top.lib mdll_r1_top.lib
    # ln -s ../build/phase_interpolator/phase_interpolator_lib.db phase_interpolator_lib.db
    # ln -s ../build/phase_interpolator/phase_interpolator.lib phase_interpolator.lib
    # ln -s ../build/input_divider/input_divider_lib.db input_divider_lib.db
    # ln -s ../build/input_divider/input_divider.lib input_divider.lib
    # ln -s ../build/termination/termination_lib.db termination_lib.db
    # ln -s ../build/termination/termination.lib termination.lib

inputs:
  - adk

outputs:
  - prbs_generator_syn_lib.db
  - prbs_generator_syn.lib
  - hr_16t4_mux_top_lib.db
  - hr_16t4_mux_top.lib
  - qr_4t1_mux_top_lib.db
  - qr_4t1_mux_top.lib

parameters:
  # Name of the technology library containing ADK_DRIVING_CELL
  qtm_tech_lib: tcbn16ffcllbwp16p90tt0p8v25c

  # Period of the main clock in nanoseconds
  # (will be scaled by constr_time_scale)
  constr_main_per: 0.7

  # Scale factor for timing constraints
  constr_time_scale: 1.0
