#=========================================================================
# LVS using netgen
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: open-netgen-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_extracted.spice
  - design.lvs.v
  - prbs_generator_syn.lvs.v
  - hr_16t4_mux_top.lvs.v
  - qr_4t1_mux_top.lvs.v
  - fine_freq_track.lvs.v
  - osc_core.lvs.v

outputs:
  - lvs_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
  - cat inputs/design.lvs.v inputs/prbs_generator_syn.lvs.v inputs/qr_4t1_mux_top.lvs.v inputs/fine_freq_track.lvs.v inputs/osc_core.lvs.v > outputs/design_merged.lvs.v
  - v2lvs -i -lsp inputs/adk/stdcells.spi -s inputs/adk/stdcells.spi -v outputs/design_merged.lvs.v -o design_lvs.spice
  - sh run_lvs.sh

preconditions:

  - assert File(inputs/design.lvs.v)
  - assert File(inputs/prbs_generator_syn.lvs.v)
  - assert File(inputs/qr_4t1_mux_top.lvs.v)
  - assert File(inputs/fine_freq_track.lvs.v)
  - assert File(inputs/osc_core.lvs.v)

postconditions:

  - assert File(outputs/design_merged.lvs.v)