#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-place

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - cell-grouping.tcl

parameters:
  num_mem_tiles: 4
